.. admonition:: Tutorial tasks

    1.  Create a crystal structure for the material of your choosing.
        Create a cell and a set of atoms. Specify all mentioned properties for each atom.
    #.  (extra) Visualize your structure using :py:class:`magnopy.PlotlyEngine`
    #.  (extra) Compute conventional and primitive cell for your structure (see
        :py:func:`wulfric.crystal.get_primitive` and
        :py:func:`wulfric.crystal.get_conventional`). Visualize them. Are they
        they the same for your crystal? Shall they always be the same or not?