.. admonition:: Exercises

    *   Create a Hamiltonian for the cubic ferromagnetic model with nearest neighbors
        interactions and add some value of the magnetic field to it.
    *   Create ten Hamiltonians with the following magnetic fields:
        
        - (0, 0.1, 0)
        - (0, 0.2, 0)
        - (0, 0.3, 0)
        - (0, 0.4, 0)
        - (0, 0.5, 0)
        - (0, 0.6, 0)
        - (0, 0.7, 0)
        - (0, 0.8, 0)
        - (0, 0.9, 0)
        - (0, 1.0, 0)

        .. hint:: 

            Use arithmetic operations on the Hamiltonians.