.. admonition:: Exercises

    *   Compute classical energy of one of the Hamiltonians from the previous tasks.
    *   Change the convention of the spin Hamiltonian and compute the energy again.
        Does it change?
    *   Create a Hamiltonian with the isotropic exchange, triaxial anisotropy and DM
        interaction. Optimize the spin direction for the full Hamiltonian. Use them to
        compute energy contributions of every term.
    *   (extra) Create a Hamiltonian of the ferromagnet with an easy magnetic axis.
        Find out numerically the value of the magnetic field that shall be applied
        perpendicular to the easy axis, which fully orients the spins along the magnetic
        field.