.. admonition:: Exercises

    * Create a crystal structure, in which conventional and primitive cells are the same.
      Compute k-points and k-path for it.
    * Create a crystal structure, in which original cell is neither conventional nor
      primitive. Compute k-points and k-path for it.
    * For the crystal structure from this page compute k-points and k-path for the 
      (2, 3, 1) super-cell. Compare high-symmetry points and k-path with those of the
      original cell.
    * For the crystal structure from this page compute k-points and k-path for the 
      (2, 3, 1) super-cell, modifying the ``spglib_types`` in such a way that same atoms 
      of the original cell that are located in different "sub-cells" of the super-cell
      have different ``spglib_types``. Compare high-symmetry points and k-path with those
      of the original cell.